name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '要部署的分支'
        required: true
        default: 'retype-setup'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install -g retypeapp

      - run: retype build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _retype

      - uses: actions/deploy-pages@v4
        id: deployment
