name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '要部署的分支'
        required: true
        default: 'retype-setup'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - uses: retypeapp/action-build@latest
      - uses: retypeapp/action-github-pages@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
