name: Deploy to GitHub Pages

on:
  push:
    branches: [retype-setup]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: retypeapp/action-build@latest
      - uses: retypeapp/action-github-pages@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
